export default {
  product: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      ratting: 4.5,
      numReviews: 10,
      countInStock: 60,
    },
    {
      _id: "2",
      name: "Long pent",
      category: "Pent",
      image: "/images/d1.jpg",
      price: 40,
      brand: "adidas",
      ratting: 4.5,
      numReviews: 10,
      countInStock: 8,
    },
    {
      _id: "3",
      name: "Fit Shirt",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 70,
      brand: "supreme",
      ratting: 4.5,
      numReviews: 10,
      countInStock: 11,
    },
  ],
};
